### ISSUE TITLE
python main.py command not starting the server correctly

### ISSUE THREAD

**Issue by otilor** [sojjyCodes/G-Search#1]
Hey @sojjyCodes, After cloning the project I tried using python main.py to start the server but this failed.

It gave me a response like this `AttributeError: TCPServer instance has no attribute '__exit__'`

I tried using `python3 main.py` and this fixed the problem. I'd like you to update your README file to contain the correct command for starting the server.

**Comment by sojjyCodes** [comment]
@GabielFemi, thanks for your report it has been fixed feel free to try it now.
